import type { PageTemplate } from './types.js'

/**
 * "Invitación de Cumpleaños" — colorful, playful birthday party invite.
 *
 * Card 1 (hidden): QR business card.
 * Card 2: Big "Feliz Cumpleaños" headline + balloons.
 * Card 3: Event details (date / time / place).
 * Card 4: RSVP card.
 */
export const birthdayInvitation: PageTemplate = {
  id: 'birthday-invitation',
  name: 'Invitación de Cumpleaños 🎂',
  description: 'Una invitación alegre para celebrar tu día especial.',
  emoji: '🎂',
  defaultTitle: '¡Estás invitado a mi cumpleaños! 🎉',
  canvases: [
    {
      background: '#fff5f7',
      width: 400,
      height: 600,
      visible: false,
      elements: [],
    },
    {
      background: '#fdf2f8',
      width: 800,
      height: 600,
      visible: true,
      elements: [
        {
          id: 'b-1',
          type: 'text',
          x: 50,
          y: 80,
          width: 700,
          height: 100,
          content: '¡Feliz Cumpleaños!',
          fontSize: 60,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'Georgia, serif',
          color: '#db2777',
        },
        {
          id: 'b-2',
          type: 'text',
          x: 50,
          y: 200,
          width: 700,
          height: 60,
          content: 'Acompáñame a celebrar mi día especial 🎉',
          fontSize: 22,
          fontWeight: 'normal',
          fontStyle: 'italic',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'sans-serif',
          color: '#831843',
        },
        {
          id: 'b-3',
          type: 'shape',
          shape: 'circle',
          x: 130,
          y: 280,
          width: 70,
          height: 70,
          color: '#f472b6',
        },
        {
          id: 'b-4',
          type: 'shape',
          shape: 'circle',
          x: 230,
          y: 300,
          width: 60,
          height: 60,
          color: '#a78bfa',
        },
        {
          id: 'b-5',
          type: 'shape',
          shape: 'circle',
          x: 520,
          y: 280,
          width: 70,
          height: 70,
          color: '#fb923c',
        },
        {
          id: 'b-6',
          type: 'shape',
          shape: 'circle',
          x: 610,
          y: 300,
          width: 60,
          height: 60,
          color: '#34d399',
        },
        {
          id: 'b-7',
          type: 'shape',
          shape: 'star',
          x: 360,
          y: 110,
          width: 40,
          height: 40,
          color: '#facc15',
        },
        {
          id: 'b-8',
          type: 'shape',
          shape: 'star',
          x: 410,
          y: 130,
          width: 30,
          height: 30,
          color: '#facc15',
        },
        {
          id: 'b-9',
          type: 'text',
          x: 50,
          y: 470,
          width: 700,
          height: 80,
          content: '🎂',
          fontSize: 64,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'sans-serif',
          color: '#000000',
        },
      ],
    },
    {
      background: '#fff7ed',
      width: 800,
      height: 600,
      visible: true,
      elements: [
        {
          id: 'b-10',
          type: 'text',
          x: 50,
          y: 60,
          width: 700,
          height: 70,
          content: 'Cuándo y dónde',
          fontSize: 40,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'Georgia, serif',
          color: '#9a3412',
        },
        {
          id: 'b-11',
          type: 'text',
          x: 100,
          y: 160,
          width: 600,
          height: 60,
          content: '📅 Fecha',
          fontSize: 22,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#7c2d12',
        },
        {
          id: 'b-12',
          type: 'text',
          x: 100,
          y: 220,
          width: 600,
          height: 60,
          content: 'Sábado 15 de Marzo, 2026',
          fontSize: 24,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#1f2937',
        },
        {
          id: 'b-13',
          type: 'text',
          x: 100,
          y: 300,
          width: 600,
          height: 60,
          content: '🕒 Hora',
          fontSize: 22,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#7c2d12',
        },
        {
          id: 'b-14',
          type: 'text',
          x: 100,
          y: 360,
          width: 600,
          height: 60,
          content: '8:00 PM — hasta que el cuerpo aguante',
          fontSize: 24,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#1f2937',
        },
        {
          id: 'b-15',
          type: 'text',
          x: 100,
          y: 440,
          width: 600,
          height: 60,
          content: '📍 Lugar',
          fontSize: 22,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#7c2d12',
        },
        {
          id: 'b-16',
          type: 'text',
          x: 100,
          y: 500,
          width: 600,
          height: 60,
          content: 'Salón "A Celebrar" — Av. Fiesta 123',
          fontSize: 24,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#1f2937',
        },
      ],
    },
    {
      background: '#fef3c7',
      width: 800,
      height: 600,
      visible: true,
      elements: [
        {
          id: 'b-17',
          type: 'text',
          x: 50,
          y: 80,
          width: 700,
          height: 80,
          content: '¿Vienes? 🥳',
          fontSize: 52,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'Georgia, serif',
          color: '#92400e',
        },
        {
          id: 'b-18',
          type: 'text',
          x: 80,
          y: 200,
          width: 640,
          height: 200,
          content: 'Confirma tu asistencia antes del 10 de marzo. ¡Tu presencia hará que mi día sea inolvidable!',
          fontSize: 22,
          fontWeight: 'normal',
          fontStyle: 'italic',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'Georgia, serif',
          color: '#451a03',
        },
        {
          id: 'b-19',
          type: 'shape',
          shape: 'heart',
          x: 370,
          y: 410,
          width: 60,
          height: 60,
          color: '#dc2626',
        },
        {
          id: 'b-20',
          type: 'text',
          x: 50,
          y: 490,
          width: 700,
          height: 60,
          content: '¡Te espero! 💖',
          fontSize: 28,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'sans-serif',
          color: '#92400e',
        },
      ],
    },
  ],
}
