import type { PageTemplate } from './types.js'

/**
 * "Invitación a Graduación" — academic-themed, blue + gold graduation invite.
 *
 * Card 1 (hidden): QR business card.
 * Card 2: Big "¡Me gradué!" headline with cap-and-diploma feel.
 * Card 3: Ceremony details (date / time / place).
 * Card 4: "Celebremos juntos" RSVP.
 */
export const graduationInvitation: PageTemplate = {
  id: 'graduation-invitation',
  name: 'Invitación a Graduación 🎓',
  description: 'Comparte tu logro académico e invita a celebrar en grande.',
  emoji: '🎓',
  defaultTitle: '¡Me gradué! 🎓 — Acompáñame a celebrar',
  canvases: [
    {
      background: '#fef3c7',
      width: 400,
      height: 600,
      visible: false,
      elements: [],
    },
    {
      background: '#1e3a8a',
      width: 800,
      height: 600,
      visible: true,
      elements: [
        {
          id: 'g-1',
          type: 'text',
          x: 50,
          y: 70,
          width: 700,
          height: 80,
          content: '¡Me gradué!',
          fontSize: 72,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'Georgia, serif',
          color: '#fbbf24',
        },
        {
          id: 'g-2',
          type: 'text',
          x: 50,
          y: 180,
          width: 700,
          height: 60,
          content: 'Después de años de esfuerzo, lo logré 🎓',
          fontSize: 22,
          fontWeight: 'normal',
          fontStyle: 'italic',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'sans-serif',
          color: '#dbeafe',
        },
        {
          id: 'g-3',
          type: 'shape',
          shape: 'star',
          x: 200,
          y: 280,
          width: 60,
          height: 60,
          color: '#fbbf24',
        },
        {
          id: 'g-4',
          type: 'shape',
          shape: 'star',
          x: 370,
          y: 280,
          width: 60,
          height: 60,
          color: '#fbbf24',
        },
        {
          id: 'g-5',
          type: 'shape',
          shape: 'star',
          x: 540,
          y: 280,
          width: 60,
          height: 60,
          color: '#fbbf24',
        },
        {
          id: 'g-6',
          type: 'shape',
          shape: 'plus',
          x: 130,
          y: 360,
          width: 30,
          height: 30,
          color: '#fbbf24',
        },
        {
          id: 'g-7',
          type: 'shape',
          shape: 'plus',
          x: 640,
          y: 360,
          width: 30,
          height: 30,
          color: '#fbbf24',
        },
        {
          id: 'g-8',
          type: 'shape',
          shape: 'plus',
          x: 280,
          y: 410,
          width: 30,
          height: 30,
          color: '#fbbf24',
        },
        {
          id: 'g-9',
          type: 'shape',
          shape: 'plus',
          x: 490,
          y: 410,
          width: 30,
          height: 30,
          color: '#fbbf24',
        },
        {
          id: 'g-10',
          type: 'text',
          x: 50,
          y: 470,
          width: 700,
          height: 60,
          content: '🎓 Ingeniería en Sistemas — Generación 2026 🎓',
          fontSize: 20,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'sans-serif',
          color: '#fef3c7',
        },
      ],
    },
    {
      background: '#fef3c7',
      width: 800,
      height: 600,
      visible: true,
      elements: [
        {
          id: 'g-11',
          type: 'text',
          x: 50,
          y: 50,
          width: 700,
          height: 70,
          content: 'Ceremonia de Graduación',
          fontSize: 40,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'Georgia, serif',
          color: '#1e3a8a',
        },
        {
          id: 'g-12',
          type: 'text',
          x: 100,
          y: 150,
          width: 600,
          height: 60,
          content: '📅 Fecha',
          fontSize: 22,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#1e40af',
        },
        {
          id: 'g-13',
          type: 'text',
          x: 100,
          y: 210,
          width: 600,
          height: 60,
          content: 'Viernes 26 de Junio, 2026',
          fontSize: 24,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#1f2937',
        },
        {
          id: 'g-14',
          type: 'text',
          x: 100,
          y: 290,
          width: 600,
          height: 60,
          content: '🕒 Hora',
          fontSize: 22,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#1e40af',
        },
        {
          id: 'g-15',
          type: 'text',
          x: 100,
          y: 350,
          width: 600,
          height: 60,
          content: '6:00 PM — Recepción · 7:00 PM — Ceremonia',
          fontSize: 24,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#1f2937',
        },
        {
          id: 'g-16',
          type: 'text',
          x: 100,
          y: 430,
          width: 600,
          height: 60,
          content: '📍 Lugar',
          fontSize: 22,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#1e40af',
        },
        {
          id: 'g-17',
          type: 'text',
          x: 100,
          y: 490,
          width: 600,
          height: 60,
          content: 'Auditorio Principal de la Universidad',
          fontSize: 24,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#1f2937',
        },
      ],
    },
    {
      background: '#1e3a8a',
      width: 800,
      height: 600,
      visible: true,
      elements: [
        {
          id: 'g-18',
          type: 'text',
          x: 50,
          y: 70,
          width: 700,
          height: 80,
          content: '¡Celebremos juntos!',
          fontSize: 52,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'Georgia, serif',
          color: '#fbbf24',
        },
        {
          id: 'g-19',
          type: 'text',
          x: 80,
          y: 180,
          width: 640,
          height: 200,
          content: 'No sería lo mismo sin ti. Comparte conmigo este momento tan especial y luego brindemos por los nuevos caminos que se abren.',
          fontSize: 20,
          fontWeight: 'normal',
          fontStyle: 'italic',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'Georgia, serif',
          color: '#dbeafe',
        },
        {
          id: 'g-20',
          type: 'shape',
          shape: 'star',
          x: 370,
          y: 400,
          width: 60,
          height: 60,
          color: '#fbbf24',
        },
        {
          id: 'g-21',
          type: 'text',
          x: 50,
          y: 490,
          width: 700,
          height: 60,
          content: '¡Confirma tu asistencia! 🎉',
          fontSize: 24,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'sans-serif',
          color: '#fbbf24',
        },
      ],
    },
  ],
}
