import type { PageTemplate } from './types.js'

/**
 * "Propuesta de Matrimonio" — formal, elegant marriage-proposal composition.
 *
 * Card 1 (hidden): QR business card.
 * Card 2: A timeless black-and-gold headline card.
 * Card 3: Our story / timeline.
 * Card 4: The big question with a ring and a heart.
 */
export const marriageProposal: PageTemplate = {
  id: 'marriage-proposal',
  name: 'Propuesta de Matrimonio 💍',
  description: 'Una propuesta elegante y emotiva para el momento más importante.',
  emoji: '💍',
  defaultTitle: 'Propuesta de Matrimonio 💍',
  canvases: [
    {
      background: '#0f172a',
      width: 400,
      height: 600,
      visible: false,
      elements: [],
    },
    {
      background: '#0f172a',
      width: 800,
      height: 600,
      visible: true,
      elements: [
        {
          id: 'm-1',
          type: 'text',
          x: 50,
          y: 80,
          width: 700,
          height: 100,
          content: 'Una pregunta para siempre',
          fontSize: 48,
          fontWeight: 'normal',
          fontStyle: 'italic',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'Georgia, serif',
          color: '#fbbf24',
        },
        {
          id: 'm-2',
          type: 'text',
          x: 50,
          y: 200,
          width: 700,
          height: 120,
          content: '¿Te casarías conmigo?',
          fontSize: 64,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'Georgia, serif',
          color: '#fef3c7',
        },
        {
          id: 'm-3',
          type: 'shape',
          shape: 'check',
          x: 370,
          y: 380,
          width: 60,
          height: 60,
          color: '#fbbf24',
        },
        {
          id: 'm-4',
          type: 'shape',
          shape: 'lightning',
          x: 250,
          y: 320,
          width: 40,
          height: 40,
          color: '#fbbf24',
        },
        {
          id: 'm-5',
          type: 'shape',
          shape: 'lightning',
          x: 510,
          y: 320,
          width: 40,
          height: 40,
          color: '#fbbf24',
        },
        {
          id: 'm-6',
          type: 'text',
          x: 50,
          y: 480,
          width: 700,
          height: 60,
          content: '— Una vida juntos, mi amor —',
          fontSize: 22,
          fontWeight: 'normal',
          fontStyle: 'italic',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'Georgia, serif',
          color: '#fbbf24',
        },
      ],
    },
    {
      background: '#fef3c7',
      width: 800,
      height: 600,
      visible: true,
      elements: [
        {
          id: 'm-7',
          type: 'text',
          x: 50,
          y: 50,
          width: 700,
          height: 70,
          content: 'Nuestra historia hasta hoy',
          fontSize: 36,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'Georgia, serif',
          color: '#92400e',
        },
        {
          id: 'm-8',
          type: 'shape',
          shape: 'heart',
          x: 180,
          y: 150,
          width: 50,
          height: 50,
          color: '#dc2626',
        },
        {
          id: 'm-9',
          type: 'shape',
          shape: 'heart',
          x: 375,
          y: 150,
          width: 50,
          height: 50,
          color: '#dc2626',
        },
        {
          id: 'm-10',
          type: 'shape',
          shape: 'heart',
          x: 570,
          y: 150,
          width: 50,
          height: 50,
          color: '#dc2626',
        },
        {
          id: 'm-11',
          type: 'text',
          x: 100,
          y: 220,
          width: 200,
          height: 80,
          content: 'El día que nos conocimos',
          fontSize: 18,
          fontWeight: 'normal',
          fontStyle: 'italic',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'Georgia, serif',
          color: '#451a03',
        },
        {
          id: 'm-12',
          type: 'text',
          x: 300,
          y: 220,
          width: 200,
          height: 80,
          content: 'La primera vez que dijiste "sí"',
          fontSize: 18,
          fontWeight: 'normal',
          fontStyle: 'italic',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'Georgia, serif',
          color: '#451a03',
        },
        {
          id: 'm-13',
          type: 'text',
          x: 500,
          y: 220,
          width: 200,
          height: 80,
          content: 'Y todos los momentos desde entonces',
          fontSize: 18,
          fontWeight: 'normal',
          fontStyle: 'italic',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'Georgia, serif',
          color: '#451a03',
        },
        {
          id: 'm-14',
          type: 'shape',
          shape: 'plus',
          x: 120,
          y: 320,
          width: 560,
          height: 10,
          color: '#a16207',
        },
        {
          id: 'm-15',
          type: 'text',
          x: 80,
          y: 360,
          width: 640,
          height: 200,
          content: '"Cada día a tu lado es un regalo. Quiero despertar a tu lado el resto de mi vida, construir más recuerdos contigo y envejecer tomados de la mano."',
          fontSize: 20,
          fontWeight: 'normal',
          fontStyle: 'italic',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'Georgia, serif',
          color: '#78350f',
        },
      ],
    },
    {
      background: '#0f172a',
      width: 800,
      height: 600,
      visible: true,
      elements: [
        {
          id: 'm-16',
          type: 'text',
          x: 50,
          y: 60,
          width: 700,
          height: 60,
          content: 'Mi respuesta es sí a todo contigo...',
          fontSize: 22,
          fontWeight: 'normal',
          fontStyle: 'italic',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'Georgia, serif',
          color: '#fbbf24',
        },
        {
          id: 'm-17',
          type: 'text',
          x: 50,
          y: 150,
          width: 700,
          height: 110,
          content: '¿La tuya también?',
          fontSize: 56,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'Georgia, serif',
          color: '#fef3c7',
        },
        {
          id: 'm-18',
          type: 'shape',
          shape: 'heart',
          x: 320,
          y: 290,
          width: 160,
          height: 160,
          color: '#fbbf24',
        },
        {
          id: 'm-19',
          type: 'text',
          x: 50,
          y: 480,
          width: 700,
          height: 60,
          content: 'Di "sí" 💍',
          fontSize: 28,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'Georgia, serif',
          color: '#fbbf24',
        },
      ],
    },
  ],
}
