import type { PageTemplate } from './types.js'

/**
 * "Restaurante Profesional" — elegant multi-card restaurant page.
 *
 * Card 1 (hidden): QR business card.
 * Card 2: Hero — restaurant name, tagline, ambiance.
 * Card 3: Menu highlights — starters, mains, desserts.
 * Card 4: Drinks & cocktails.
 * Card 5: Hours & location.
 * Card 6: Reservation / contact.
 */
export const restaurant: PageTemplate = {
  id: 'restaurant-menu',
  name: 'Menú de Restaurante 🍽️',
  description: 'Página profesional para restaurante con menú, bebidas, horarios y reservaciones.',
  emoji: '🍽️',
  defaultTitle: 'Restaurante — Menú y Reservaciones',
  canvases: [
    {
      background: '#1c1917',
      width: 400,
      height: 600,
      visible: false,
      elements: [],
    },
    {
      background: '#1c1917',
      width: 800,
      height: 600,
      visible: true,
      elements: [
        {
          id: 'r-1',
          type: 'shape',
          shape: 'diamond',
          x: 380,
          y: 30,
          width: 40,
          height: 40,
          color: '#d97706',
        },
        {
          id: 'r-2',
          type: 'text',
          x: 50,
          y: 90,
          width: 700,
          height: 90,
          content: 'La Casa Dorada',
          fontSize: 56,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'Georgia, serif',
          color: '#fbbf24',
        },
        {
          id: 'r-3',
          type: 'text',
          x: 100,
          y: 190,
          width: 600,
          height: 50,
          content: 'Sabor tradicional con toque moderno',
          fontSize: 22,
          fontWeight: 'normal',
          fontStyle: 'italic',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'Georgia, serif',
          color: '#d6d3d1',
        },
        {
          id: 'r-4',
          type: 'shape',
          shape: 'plus',
          x: 385,
          y: 255,
          width: 30,
          height: 30,
          color: '#d97706',
        },
        {
          id: 'r-5',
          type: 'text',
          x: 100,
          y: 300,
          width: 600,
          height: 60,
          content: 'Cocina fusión · Vinos selectos · Experiencia única',
          fontSize: 18,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'sans-serif',
          color: '#a8a29e',
        },
        {
          id: 'r-6',
          type: 'text',
          x: 180,
          y: 400,
          width: 120,
          height: 80,
          content: '🍷',
          fontSize: 52,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'sans-serif',
          color: '#000000',
        },
        {
          id: 'r-7',
          type: 'text',
          x: 340,
          y: 390,
          width: 120,
          height: 80,
          content: '🥩',
          fontSize: 56,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'sans-serif',
          color: '#000000',
        },
        {
          id: 'r-8',
          type: 'text',
          x: 500,
          y: 400,
          width: 120,
          height: 80,
          content: '🍰',
          fontSize: 52,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'sans-serif',
          color: '#000000',
        },
        {
          id: 'r-9',
          type: 'navigation',
          x: 80,
          y: 500,
          width: 640,
          height: 60,
          items: [
            { label: '🍽️ Menú', targetCard: 1 },
            { label: '🍷 Bebidas', targetCard: 2 },
            { label: '🕐 Horarios', targetCard: 3 },
            { label: '📞 Reservar', targetCard: 4 },
          ],
          buttonColor: '#d97706',
          buttonTextColor: '#ffffff',
          borderRadius: 8,
          gap: 10,
        },
      ],
    },
    {
      background: '#fefce8',
      width: 800,
      height: 600,
      visible: true,
      elements: [
        {
          id: 'r-10',
          type: 'text',
          x: 50,
          y: 30,
          width: 700,
          height: 60,
          content: 'Nuestro Menú',
          fontSize: 40,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'Georgia, serif',
          color: '#713f12',
        },
        {
          id: 'r-11',
          type: 'text',
          x: 60,
          y: 100,
          width: 300,
          height: 40,
          content: '🥗 Entradas',
          fontSize: 22,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#92400e',
        },
        {
          id: 'r-12',
          type: 'text',
          x: 60,
          y: 140,
          width: 500,
          height: 30,
          content: 'Bruschetta de tomate y albahaca fresca',
          fontSize: 16,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#44403c',
        },
        {
          id: 'r-13',
          type: 'text',
          x: 600,
          y: 140,
          width: 150,
          height: 30,
          content: '$180',
          fontSize: 16,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'right',
          fontFamily: 'sans-serif',
          color: '#92400e',
        },
        {
          id: 'r-14',
          type: 'text',
          x: 60,
          y: 175,
          width: 500,
          height: 30,
          content: 'Carpaccio de res con rúcula y parmesano',
          fontSize: 16,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#44403c',
        },
        {
          id: 'r-15',
          type: 'text',
          x: 600,
          y: 175,
          width: 150,
          height: 30,
          content: '$220',
          fontSize: 16,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'right',
          fontFamily: 'sans-serif',
          color: '#92400e',
        },
        {
          id: 'r-16',
          type: 'text',
          x: 60,
          y: 210,
          width: 500,
          height: 30,
          content: 'Sopa del día con pan artesanal',
          fontSize: 16,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#44403c',
        },
        {
          id: 'r-17',
          type: 'text',
          x: 600,
          y: 210,
          width: 150,
          height: 30,
          content: '$150',
          fontSize: 16,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'right',
          fontFamily: 'sans-serif',
          color: '#92400e',
        },
        {
          id: 'r-18',
          type: 'text',
          x: 60,
          y: 270,
          width: 300,
          height: 40,
          content: '🥩 Platos Fuertes',
          fontSize: 22,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#92400e',
        },
        {
          id: 'r-19',
          type: 'text',
          x: 60,
          y: 310,
          width: 500,
          height: 30,
          content: 'Ribeye 300g con puré de trufa y asparagus',
          fontSize: 16,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#44403c',
        },
        {
          id: 'r-20',
          type: 'text',
          x: 600,
          y: 310,
          width: 150,
          height: 30,
          content: '$480',
          fontSize: 16,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'right',
          fontFamily: 'sans-serif',
          color: '#92400e',
        },
        {
          id: 'r-21',
          type: 'text',
          x: 60,
          y: 345,
          width: 500,
          height: 30,
          content: 'Salmón a la parrilla con risotto de limón',
          fontSize: 16,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#44403c',
        },
        {
          id: 'r-22',
          type: 'text',
          x: 600,
          y: 345,
          width: 150,
          height: 30,
          content: '$420',
          fontSize: 16,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'right',
          fontFamily: 'sans-serif',
          color: '#92400e',
        },
        {
          id: 'r-23',
          type: 'text',
          x: 60,
          y: 380,
          width: 500,
          height: 30,
          content: 'Pasta artesanal con crema de boletus',
          fontSize: 16,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#44403c',
        },
        {
          id: 'r-24',
          type: 'text',
          x: 600,
          y: 380,
          width: 150,
          height: 30,
          content: '$350',
          fontSize: 16,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'right',
          fontFamily: 'sans-serif',
          color: '#92400e',
        },
        {
          id: 'r-25',
          type: 'text',
          x: 60,
          y: 440,
          width: 300,
          height: 40,
          content: '🍰 Postres',
          fontSize: 22,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#92400e',
        },
        {
          id: 'r-26',
          type: 'text',
          x: 60,
          y: 480,
          width: 500,
          height: 30,
          content: 'Tiramisú de chocolate belga',
          fontSize: 16,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#44403c',
        },
        {
          id: 'r-27',
          type: 'text',
          x: 600,
          y: 480,
          width: 150,
          height: 30,
          content: '$180',
          fontSize: 16,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'right',
          fontFamily: 'sans-serif',
          color: '#92400e',
        },
        {
          id: 'r-28',
          type: 'text',
          x: 60,
          y: 515,
          width: 500,
          height: 30,
          content: 'Crème brûlée de vainilla bourbon',
          fontSize: 16,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#44403c',
        },
        {
          id: 'r-29',
          type: 'text',
          x: 600,
          y: 515,
          width: 150,
          height: 30,
          content: '$160',
          fontSize: 16,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'right',
          fontFamily: 'sans-serif',
          color: '#92400e',
        },
        {
          id: 'r-30',
          type: 'text',
          x: 60,
          y: 550,
          width: 500,
          height: 30,
          content: 'Tarta de queso con frutos rojos',
          fontSize: 16,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#44403c',
        },
        {
          id: 'r-31',
          type: 'text',
          x: 600,
          y: 550,
          width: 150,
          height: 30,
          content: '$170',
          fontSize: 16,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'right',
          fontFamily: 'sans-serif',
          color: '#92400e',
        },
      ],
    },
    {
      background: '#1e1b4b',
      width: 800,
      height: 600,
      visible: true,
      elements: [
        {
          id: 'r-32',
          type: 'text',
          x: 50,
          y: 30,
          width: 700,
          height: 60,
          content: 'Vinos y Cócteles',
          fontSize: 40,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'Georgia, serif',
          color: '#c4b5fd',
        },
        {
          id: 'r-33',
          type: 'text',
          x: 360,
          y: 85,
          width: 80,
          height: 60,
          content: '🍷',
          fontSize: 42,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'sans-serif',
          color: '#000000',
        },
        {
          id: 'r-34',
          type: 'text',
          x: 60,
          y: 155,
          width: 300,
          height: 35,
          content: '🍇 Vinos',
          fontSize: 20,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#a78bfa',
        },
        {
          id: 'r-35',
          type: 'text',
          x: 60,
          y: 195,
          width: 480,
          height: 28,
          content: 'Malbec Reserva — Mendoza, Argentina',
          fontSize: 15,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#d4d4d8',
        },
        {
          id: 'r-36',
          type: 'text',
          x: 600,
          y: 195,
          width: 150,
          height: 28,
          content: '$380',
          fontSize: 15,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'right',
          fontFamily: 'sans-serif',
          color: '#fbbf24',
        },
        {
          id: 'r-37',
          type: 'text',
          x: 60,
          y: 228,
          width: 480,
          height: 28,
          content: 'Cabernet Sauvignon — Valle de Colchagua',
          fontSize: 15,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#d4d4d8',
        },
        {
          id: 'r-38',
          type: 'text',
          x: 600,
          y: 228,
          width: 150,
          height: 28,
          content: '$420',
          fontSize: 15,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'right',
          fontFamily: 'sans-serif',
          color: '#fbbf24',
        },
        {
          id: 'r-39',
          type: 'text',
          x: 60,
          y: 261,
          width: 480,
          height: 28,
          content: 'Chardonnay — Casablanca Valley',
          fontSize: 15,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#d4d4d8',
        },
        {
          id: 'r-40',
          type: 'text',
          x: 600,
          y: 261,
          width: 150,
          height: 28,
          content: '$360',
          fontSize: 15,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'right',
          fontFamily: 'sans-serif',
          color: '#fbbf24',
        },
        {
          id: 'r-41',
          type: 'text',
          x: 60,
          y: 320,
          width: 300,
          height: 35,
          content: '🍸 Cócteles de Autor',
          fontSize: 20,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#a78bfa',
        },
        {
          id: 'r-42',
          type: 'text',
          x: 60,
          y: 360,
          width: 480,
          height: 28,
          content: 'Golden Sunset — ron, mango, tamarindo',
          fontSize: 15,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#d4d4d8',
        },
        {
          id: 'r-43',
          type: 'text',
          x: 600,
          y: 360,
          width: 150,
          height: 28,
          content: '$220',
          fontSize: 15,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'right',
          fontFamily: 'sans-serif',
          color: '#fbbf24',
        },
        {
          id: 'r-44',
          type: 'text',
          x: 60,
          y: 393,
          width: 480,
          height: 28,
          content: 'Midnight Rose — ginebra, pétalos, rosa',
          fontSize: 15,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#d4d4d8',
        },
        {
          id: 'r-45',
          type: 'text',
          x: 600,
          y: 393,
          width: 150,
          height: 28,
          content: '$240',
          fontSize: 15,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'right',
          fontFamily: 'sans-serif',
          color: '#fbbf24',
        },
        {
          id: 'r-46',
          type: 'text',
          x: 60,
          y: 426,
          width: 480,
          height: 28,
          content: 'Smoky Old Fashioned — bourbon, tabaco',
          fontSize: 15,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#d4d4d8',
        },
        {
          id: 'r-47',
          type: 'text',
          x: 600,
          y: 426,
          width: 150,
          height: 28,
          content: '$260',
          fontSize: 15,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'right',
          fontFamily: 'sans-serif',
          color: '#fbbf24',
        },
        {
          id: 'r-48',
          type: 'text',
          x: 60,
          y: 485,
          width: 300,
          height: 35,
          content: '🥂 Sin Alcohol',
          fontSize: 20,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#a78bfa',
        },
        {
          id: 'r-49',
          type: 'text',
          x: 60,
          y: 525,
          width: 480,
          height: 28,
          content: 'Limonada de jengibre y hierbabuena',
          fontSize: 15,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#d4d4d8',
        },
        {
          id: 'r-50',
          type: 'text',
          x: 600,
          y: 525,
          width: 150,
          height: 28,
          content: '$90',
          fontSize: 15,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'right',
          fontFamily: 'sans-serif',
          color: '#fbbf24',
        },
        {
          id: 'r-51',
          type: 'text',
          x: 60,
          y: 558,
          width: 480,
          height: 28,
          content: 'Agua de coco con flor de hibiscus',
          fontSize: 15,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#d4d4d8',
        },
        {
          id: 'r-52',
          type: 'text',
          x: 600,
          y: 558,
          width: 150,
          height: 28,
          content: '$80',
          fontSize: 15,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'right',
          fontFamily: 'sans-serif',
          color: '#fbbf24',
        },
      ],
    },
    {
      background: '#f5f5f4',
      width: 800,
      height: 600,
      visible: true,
      elements: [
        {
          id: 'r-53',
          type: 'text',
          x: 50,
          y: 30,
          width: 700,
          height: 60,
          content: 'Horarios y Ubicación',
          fontSize: 38,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'Georgia, serif',
          color: '#1c1917',
        },
        {
          id: 'r-54',
          type: 'text',
          x: 360,
          y: 85,
          width: 80,
          height: 50,
          content: '🕐',
          fontSize: 36,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'sans-serif',
          color: '#000000',
        },
        {
          id: 'r-55',
          type: 'text',
          x: 100,
          y: 150,
          width: 350,
          height: 30,
          content: 'Lunes a Jueves',
          fontSize: 18,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#44403c',
        },
        {
          id: 'r-56',
          type: 'text',
          x: 450,
          y: 150,
          width: 250,
          height: 30,
          content: '12:00 PM — 10:00 PM',
          fontSize: 18,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'right',
          fontFamily: 'sans-serif',
          color: '#57534e',
        },
        {
          id: 'r-57',
          type: 'text',
          x: 100,
          y: 195,
          width: 350,
          height: 30,
          content: 'Viernes y Sábado',
          fontSize: 18,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#44403c',
        },
        {
          id: 'r-58',
          type: 'text',
          x: 450,
          y: 195,
          width: 250,
          height: 30,
          content: '12:00 PM — 12:00 AM',
          fontSize: 18,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'right',
          fontFamily: 'sans-serif',
          color: '#57534e',
        },
        {
          id: 'r-59',
          type: 'text',
          x: 100,
          y: 240,
          width: 350,
          height: 30,
          content: 'Domingos',
          fontSize: 18,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          fontFamily: 'sans-serif',
          color: '#44403c',
        },
        {
          id: 'r-60',
          type: 'text',
          x: 450,
          y: 240,
          width: 250,
          height: 30,
          content: '12:00 PM — 9:00 PM',
          fontSize: 18,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'right',
          fontFamily: 'sans-serif',
          color: '#57534e',
        },
        {
          id: 'r-61',
          type: 'shape',
          shape: 'plus',
          x: 385,
          y: 295,
          width: 30,
          height: 30,
          color: '#a8a29e',
        },
        {
          id: 'r-62',
          type: 'text',
          x: 100,
          y: 340,
          width: 600,
          height: 40,
          content: '📍 Ubicación',
          fontSize: 22,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'sans-serif',
          color: '#1c1917',
        },
        {
          id: 'r-63',
          type: 'text',
          x: 100,
          y: 390,
          width: 600,
          height: 30,
          content: 'Av. Reforma 456, Col. Centro',
          fontSize: 18,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'sans-serif',
          color: '#57534e',
        },
        {
          id: 'r-64',
          type: 'text',
          x: 100,
          y: 425,
          width: 600,
          height: 30,
          content: 'Ciudad de México, CDMX 06000',
          fontSize: 18,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'sans-serif',
          color: '#57534e',
        },
        {
          id: 'r-65',
          type: 'text',
          x: 100,
          y: 490,
          width: 600,
          height: 40,
          content: '🚗 Estacionamiento gratuito para clientes',
          fontSize: 16,
          fontWeight: 'normal',
          fontStyle: 'italic',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'sans-serif',
          color: '#78716c',
        },
        {
          id: 'r-66',
          type: 'text',
          x: 100,
          y: 530,
          width: 600,
          height: 40,
          content: '♿ Accesible para personas con discapacidad',
          fontSize: 16,
          fontWeight: 'normal',
          fontStyle: 'italic',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'sans-serif',
          color: '#78716c',
        },
      ],
    },
    {
      background: '#fffbeb',
      width: 800,
      height: 600,
      visible: true,
      elements: [
        {
          id: 'r-67',
          type: 'text',
          x: 50,
          y: 40,
          width: 700,
          height: 60,
          content: 'Reservaciones',
          fontSize: 42,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'Georgia, serif',
          color: '#78350f',
        },
        {
          id: 'r-68',
          type: 'text',
          x: 100,
          y: 130,
          width: 600,
          height: 40,
          content: '📞 Teléfono',
          fontSize: 20,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'sans-serif',
          color: '#92400e',
        },
        {
          id: 'r-69',
          type: 'text',
          x: 100,
          y: 170,
          width: 600,
          height: 35,
          content: '+52 (55) 1234-5678',
          fontSize: 24,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'sans-serif',
          color: '#1c1917',
        },
        {
          id: 'r-70',
          type: 'text',
          x: 100,
          y: 230,
          width: 600,
          height: 40,
          content: '💬 WhatsApp',
          fontSize: 20,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'sans-serif',
          color: '#92400e',
        },
        {
          id: 'r-71',
          type: 'text',
          x: 100,
          y: 270,
          width: 600,
          height: 35,
          content: '+52 (55) 9876-5432',
          fontSize: 24,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'sans-serif',
          color: '#1c1917',
        },
        {
          id: 'r-72',
          type: 'shape',
          shape: 'diamond',
          x: 380,
          y: 330,
          width: 40,
          height: 40,
          color: '#d97706',
        },
        {
          id: 'r-73',
          type: 'text',
          x: 100,
          y: 390,
          width: 600,
          height: 40,
          content: '📱 Síguenos',
          fontSize: 20,
          fontWeight: 'bold',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'sans-serif',
          color: '#92400e',
        },
        {
          id: 'r-74',
          type: 'text',
          x: 100,
          y: 430,
          width: 600,
          height: 30,
          content: '@lacasadormx — Instagram',
          fontSize: 16,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'sans-serif',
          color: '#57534e',
        },
        {
          id: 'r-75',
          type: 'text',
          x: 100,
          y: 465,
          width: 600,
          height: 30,
          content: '/LaCasaDoradaMX — Facebook',
          fontSize: 16,
          fontWeight: 'normal',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'sans-serif',
          color: '#57534e',
        },
        {
          id: 'r-76',
          type: 'text',
          x: 100,
          y: 520,
          width: 600,
          height: 50,
          content: '🍽️ ¡Te esperamos para brindar una experiencia inolvidable!',
          fontSize: 18,
          fontWeight: 'bold',
          fontStyle: 'italic',
          textDecoration: 'none',
          textAlign: 'center',
          fontFamily: 'Georgia, serif',
          color: '#78350f',
        },
      ],
    },
  ],
}
